### ISSUE TITLE
New plugin offers choice of flags.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-flagmatic#1]
![screen shot 2015-02-14 at 4 35 55 pm](https://cloud.githubusercontent.com/assets/12127/6201674/2ece2ab8-b46c-11e4-9929-6a720be42f9c.png)

This plugin is fully functional now.
I might lighten up the colors to be more like those of the ruby implementation.

**Comment by paul90** [comment]
Looks nice.

**Comment by paul90** [comment]
Published as **\+ wiki-plugin-flagmatic@0.1.0**
